// Auto-generated with scripts/fillGenresFromGoogleBooks.ts

import type { ReadingYear } from "./types";

export const readingYear2025: ReadingYear = {
  year: 2025,
  readerName: "Victoria",
  goal: 50,
  books: [
  {
    "id": "hidden-pictures",
    "title": "Hidden Pictures",
    "author": "Rekulak, Jason",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1635773106l/58938609.jpg",
    "dateFinished": "2025-01-01",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/58938609-hidden-pictures",
    "personalNote": "Such a creepy, fast-paced start to the year, and I loved how you couldn't stop talking about the twisty illustrations.",
    "pages": 356,
    "genre": "Fiction"
  },
  {
    "id": "just-for-the-summer-part-of-your-world-3",
    "title": "Just for the Summer (Part of Your World, #3)",
    "author": "Jimenez, Abby",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1693786829l/195834342.jpg",
    "dateFinished": "2025-01-08",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/195834342-just-for-the-summer",
    "personalNote": "This felt like the perfect cozy romance to curl up with, all sunshine, banter, and just the right amount of feelings.",
    "pages": 262,
    "genre": "Fiction"
  },
  {
    "id": "gone-girl",
    "title": "Gone Girl",
    "author": "Flynn, Gillian",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1626637477l/58581203.jpg",
    "dateFinished": "2025-01-12",
    "rating": 1,
    "goodreadsUrl": "https://www.goodreads.com/book/show/58581203-gone-girl",
    "personalNote": "An absolute mind-bender of a thriller, and I loved hearing your theories as you tried to outsmart the twists.",
    "pages": 497,
    "genre": "Fiction"
  },
  {
    "id": "the-wedding-people",
    "title": "The Wedding People",
    "author": "Espach, Alison",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1721919005l/177328214.jpg",
    "dateFinished": "2025-01-19",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/177328214-the-wedding-people",
    "personalNote": "I love that you got pulled into all the messy, emotional wedding energy in this one—very on brand for you.",
    "pages": 384,
    "genre": "Fiction"
  },
  {
    "id": "powerless-the-powerless-trilogy-1",
    "title": "Powerless (The Powerless Trilogy, #1)",
    "author": "Roberts, Lauren",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1687711910l/153283393.jpg",
    "dateFinished": "2025-01-24",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/153283393-powerless",
    "personalNote": "This was the fantasy obsession era officially beginning, and I loved how quickly you fell for this world.",
    "pages": 528,
    "genre": "YA Fiction"
  },
  {
    "id": "reckless-the-powerless-trilogy-2",
    "title": "Reckless (The Powerless Trilogy, #2)",
    "author": "Roberts, Lauren",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1762273981l/188365460.jpg",
    "dateFinished": "2025-01-30",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/188365460-reckless",
    "personalNote": "You dove straight into this sequel, and I loved seeing how invested you were in these characters and their chaos.",
    "pages": 396,
    "genre": "YA Fiction"
  },
  {
    "id": "the-crash",
    "title": "The Crash",
    "author": "McFadden, Freida",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1720793186l/216188969.jpg",
    "dateFinished": "2025-02-06",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/216188969-the-crash",
    "personalNote": "Another wild Freida ride that kept you turning pages, even if this one wasn't your all-time favorite of hers.",
    "pages": 384,
    "genre": "Fiction"
  },
  {
    "id": "powerful-the-powerless-trilogy-1-5",
    "title": "Powerful (The Powerless Trilogy, #1.5)",
    "author": "Roberts, Lauren",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1714460518l/205042236.jpg",
    "dateFinished": "2025-02-14",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/205042236-powerful",
    "personalNote": "I love that you even picked up the 1.5—peak dedication to a series and its little in-between moments.",
    "pages": 256,
    "genre": "YA Fiction"
  },
  {
    "id": "archer-s-voice-where-love-meets-destiny-1",
    "title": "Archer's Voice (Where Love Meets Destiny, #1)",
    "author": "Sheridan, Mia",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1538256689l/42098358.jpg",
    "dateFinished": "2025-02-17",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/42098358-archer-s-voice",
    "personalNote": "This one hit all your soft spots—quiet, emotional, and tender in a way that stuck with you after you finished.",
    "pages": 307,
    "genre": "Fiction"
  },
  {
    "id": "the-house-of-my-mother-a-daughter-s-quest-for-freedom",
    "title": "The House of My Mother: A Daughter's Quest for Freedom",
    "author": "Franke, Shari",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1729099171l/214447405.jpg",
    "dateFinished": "2025-02-23",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/214447405-the-house-of-my-mother",
    "personalNote": "I know this one was heavy at times, and I admire how you lean into stories that ask hard, honest questions.",
    "pages": 320,
    "genre": "Memoir / Biography"
  },
  {
    "id": "every-last-word",
    "title": "Every Last Word",
    "author": "Stone, Tamara Ireland",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1431016937l/23341894.jpg",
    "dateFinished": "2025-03-03",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/23341894-every-last-word",
    "personalNote": "You gravitate toward stories about mental health with so much empathy, and this one fit that perfectly.",
    "pages": 308,
    "genre": "YA Fiction"
  },
  {
    "id": "the-obsession",
    "title": "The Obsession",
    "author": "Sutanto, Jesse Q.",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1603419648l/55769250.jpg",
    "dateFinished": "2025-03-13",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/55769250-the-obsession",
    "personalNote": "A quick, twisty YA thriller that scratched the suspense itch even if it wasn't a new favorite.",
    "pages": 266,
    "genre": "YA Fiction"
  },
  {
    "id": "the-naturals-the-naturals-1",
    "title": "The Naturals (The Naturals, #1)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1620015212l/18517840.jpg",
    "dateFinished": "2025-03-16",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/18517840-the-naturals",
    "personalNote": "Watching you fall into this series and its FBI teen-prodigy vibes was so fun—exactly your kind of page-turner.",
    "pages": 254,
    "genre": "Fiction"
  },
  {
    "id": "killer-instinct-the-naturals-2",
    "title": "Killer Instinct (The Naturals, #2)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1751951405l/23491611.jpg",
    "dateFinished": "2025-03-21",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/23491611-killer-instinct",
    "personalNote": "You powered straight into book two, which says everything about how hooked you were on this crew.",
    "pages": 400,
    "genre": "Fiction"
  },
  {
    "id": "all-in-the-naturals-3",
    "title": "All In (The Naturals, #3)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1436376704l/25873191.jpg",
    "dateFinished": "2025-03-24",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/25873191-all-in",
    "personalNote": "Another dark, twisty installment that you tore through like it was nothing—peak binge-reading energy.",
    "pages": 384,
    "genre": "YA Fiction"
  },
  {
    "id": "bad-blood-the-naturals-4",
    "title": "Bad Blood (The Naturals, #4)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1466122951l/30635180.jpg",
    "dateFinished": "2025-04-13",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/30635180-bad-blood",
    "personalNote": "You closed out this arc like a champ, fully invested in solving every last mystery with them.",
    "pages": 316,
    "genre": "Fiction"
  },
  {
    "id": "fearless-the-powerless-trilogy-3",
    "title": "Fearless (The Powerless Trilogy, #3)",
    "author": "Roberts, Lauren",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1730558546l/214208274.jpg",
    "dateFinished": "2025-04-27",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/214208274-fearless",
    "personalNote": "You wrapped up this trilogy with so many feelings, and I loved hearing you process that ending.",
    "pages": 593,
    "genre": "YA Fiction"
  },
  {
    "id": "rock-paper-scissors",
    "title": "Rock Paper Scissors",
    "author": "Feeney, Alice",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1613018253l/57026221.jpg",
    "dateFinished": "2025-05-13",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/57026221-rock-paper-scissors",
    "personalNote": "A moody, atmospheric thriller that gave you plenty to side-eye even if it didn't fully steal your heart.",
    "pages": 309,
    "genre": "Fiction"
  },
  {
    "id": "wild-love-rose-hill-1",
    "title": "Wild Love (Rose Hill, #1)",
    "author": "Silver, Elsie",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1713345163l/199368721.jpg",
    "dateFinished": "2025-05-23",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/199368721-wild-love",
    "personalNote": "Small-town romance, big feelings, and all the heart—this one felt like such a comfy escape for you.",
    "pages": 466,
    "genre": "Fiction"
  },
  {
    "id": "the-tenant",
    "title": "The Tenant",
    "author": "McFadden, Freida",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1734360941l/222564068.jpg",
    "dateFinished": "2025-05-24",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/222564068-the-tenant",
    "personalNote": "Another quick, twisty Freida read that gave you exactly the kind of drama you expect from her books.",
    "pages": 368,
    "genre": "Thriller"
  },
  {
    "id": "the-stillwater-girls",
    "title": "The Stillwater Girls",
    "author": "Kent, Minka",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1548889204l/40258215.jpg",
    "dateFinished": "2025-05-26",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/40258215-the-stillwater-girls",
    "personalNote": "You really enjoyed unraveling the secrets in this one, and I loved hearing you recap all the twists.",
    "pages": 273,
    "genre": "Fiction"
  },
  {
    "id": "beautiful-boy-a-father-s-journey-through-his-son-s-addiction",
    "title": "Beautiful Boy: A Father's Journey Through His Son's Addiction",
    "author": "Sheff, David",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1530843357l/35721089.jpg",
    "dateFinished": "2025-05-31",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/35721089-beautiful-boy",
    "personalNote": "This was such an emotional, difficult read, and I'm always impressed by how much care you bring to stories like this.",
    "pages": 350,
    "genre": "Memoir / Biography"
  },
  {
    "id": "what-teachers-make-in-praise-of-the-greatest-job-in-the-world",
    "title": "What Teachers Make: In Praise of the Greatest Job in the World",
    "author": "Mali, Taylor",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1344706680l/13356032.jpg",
    "dateFinished": "2025-06-03",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/13356032-what-teachers-make",
    "personalNote": "I love that you read this as a teacher—it felt like such a perfect reminder of how much heart you bring to your job.",
    "pages": 132,
    "genre": "Education"
  },
  {
    "id": "the-girls-in-the-cabin",
    "title": "The Girls in the Cabin",
    "author": "Stephens, Caleb",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1683068304l/143704302.jpg",
    "dateFinished": "2025-06-09",
    "rating": 1,
    "goodreadsUrl": "https://www.goodreads.com/book/show/143704302-the-girls-in-the-cabin",
    "personalNote": "A dark, eerie little thriller that scratched the suspense itch while you powered through your TBR.",
    "pages": 330,
    "genre": "Fiction"
  },
  {
    "id": "the-inheritance-games-the-inheritance-games-1",
    "title": "The Inheritance Games (The Inheritance Games, #1)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1587401545l/52501482.jpg",
    "dateFinished": "2025-06-13",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/52501482-the-inheritance-games",
    "personalNote": "You had so much fun with all the puzzles, drama, and mystery in this one—it's such a you-style series.",
    "pages": 378,
    "genre": "YA Fiction"
  },
  {
    "id": "the-hawthorne-legacy-the-inheritance-games-2",
    "title": "The Hawthorne Legacy (The Inheritance Games, #2)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1617809112l/56442293.jpg",
    "dateFinished": "2025-07-17",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/56442293-the-hawthorne-legacy",
    "personalNote": "You jumped right back into the Hawthorne madness, and I loved how invested you were in every reveal.",
    "pages": 384,
    "genre": "YA Fiction"
  },
  {
    "id": "the-summer-of-broken-rules",
    "title": "The Summer of Broken Rules",
    "author": "Walther, K.L.",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1618108395l/57690252.jpg",
    "dateFinished": "2025-07-23",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/57690252-the-summer-of-broken-rules",
    "personalNote": "A sweet, summery romance that gave you all the Martha's Vineyard vibes, even if it didn't fully become a fave.",
    "pages": 244,
    "genre": "YA Fiction"
  },
  {
    "id": "keeping-13-boys-of-tommen-2",
    "title": "Keeping 13 (Boys of Tommen, #2)",
    "author": "Walsh, Chloe",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1698653875l/146943394.jpg",
    "dateFinished": "2025-08-03",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/146943394-keeping-13",
    "personalNote": "You were absolutely *in it* with this book—so many feelings, so much angst, and you loved every second.",
    "pages": 994,
    "genre": "YA Fiction"
  },
  {
    "id": "my-sister-s-keeper",
    "title": "My Sister's Keeper",
    "author": "Picoult, Jodi",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1369504683l/10917.jpg",
    "dateFinished": "2025-08-10",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/10917.My_Sister_s_Keeper",
    "personalNote": "This was such an emotional roller coaster, and I loved hearing you unpack all the ethical what-ifs afterward.",
    "pages": 611,
    "genre": "Fiction"
  },
  {
    "id": "the-friend-zone-the-friend-zone-1",
    "title": "The Friend Zone (The Friend Zone, #1)",
    "author": "Jimenez, Abby",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553782344l/42774138.jpg",
    "dateFinished": "2025-08-11",
    "rating": 1,
    "goodreadsUrl": "https://www.goodreads.com/book/show/42774138-the-friend-zone",
    "personalNote": "Classic Abby mix of humor and heavier topics, and I loved hearing your thoughts on how she balanced both.",
    "pages": 372,
    "genre": "Fiction"
  },
  {
    "id": "regretting-you",
    "title": "Regretting You",
    "author": "Hoover, Colleen",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1760993353l/44582454.jpg",
    "dateFinished": "2025-08-16",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/44582454-regretting-you",
    "personalNote": "You flew through this one, fully invested in the messy family dynamics and all the CoHo drama.",
    "pages": 375,
    "genre": "Fiction"
  },
  {
    "id": "do-not-disturb",
    "title": "Do Not Disturb",
    "author": "McFadden, Freida",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629082970l/58778536.jpg",
    "dateFinished": "2025-08-18",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/58778536-do-not-disturb",
    "personalNote": "Another quick, twisty motel-style thriller that you inhaled in no time.",
    "pages": 325,
    "genre": "Fiction"
  },
  {
    "id": "saving-6-boys-of-tommen-3",
    "title": "Saving 6 (Boys of Tommen, #3)",
    "author": "Walsh, Chloe",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1743767749l/146943389.jpg",
    "dateFinished": "2025-08-23",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/146943389-saving-6",
    "personalNote": "You were so emotionally attached to these characters by this point, and it made this book hit extra hard.",
    "pages": 621,
    "genre": "Fiction"
  },
  {
    "id": "redeeming-6-boys-of-tommen-4",
    "title": "Redeeming 6 (Boys of Tommen, #4)",
    "author": "Walsh, Chloe",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1716911736l/146943908.jpg",
    "dateFinished": "2025-08-29",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/146943908-redeeming-6",
    "personalNote": "You closed out this part of the Tommen saga like a champ, heart thoroughly destroyed in the best way.",
    "pages": 776,
    "genre": "YA Fiction"
  },
  {
    "id": "taming-7-boys-of-tommen-5",
    "title": "Taming 7 (Boys of Tommen, #5)",
    "author": "Walsh, Chloe",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1692404529l/196219692.jpg",
    "dateFinished": "2025-09-07",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/196219692-taming-7",
    "personalNote": "By now this series was basically your entire personality, and I loved watching you live in this world.",
    "pages": 464,
    "genre": "YA Fiction"
  },
  {
    "id": "a-hue-of-blu-the-unforgettable-love-story",
    "title": "A Hue of Blu: the unforgettable love story",
    "author": "Léger, Marie-France",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1719010316l/213587168.jpg",
    "dateFinished": "2025-09-15",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/213587168-a-hue-of-blu",
    "personalNote": "A unique little love story that added something different to your romance streak this year.",
    "pages": 384,
    "genre": "Romance"
  },
  {
    "id": "releasing-10-boys-of-tommen-6",
    "title": "Releasing 10 (Boys of Tommen, #6)",
    "author": "Walsh, Chloe",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1745299737l/229717312.jpg",
    "dateFinished": "2025-09-22",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/229717312-releasing-10",
    "personalNote": "You weren't ready to leave this world yet, and I loved seeing how attached you were to these characters.",
    "pages": 765,
    "genre": "YA Fiction"
  },
  {
    "id": "divine-rivals-letters-of-enchantment-1",
    "title": "Divine Rivals (Letters of Enchantment, #1)",
    "author": "Ross, Rebecca",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1661929417l/62202008.jpg",
    "dateFinished": "2025-09-28",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/62202008-divine-rivals",
    "personalNote": "Typewriters, letters, war, and magic—this felt like such a beautifully soft, romantic fantasy for you.",
    "pages": 323,
    "genre": "YA Fiction"
  },
  {
    "id": "ruthless-vows-letters-of-enchantment-2",
    "title": "Ruthless Vows (Letters of Enchantment, #2)",
    "author": "Ross, Rebecca",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1684911502l/150260787.jpg",
    "dateFinished": "2025-10-04",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/150260787-ruthless-vows",
    "personalNote": "You were glad to see how the story wrapped up, even if this one didn't quite hit as hard as the first.",
    "pages": 419,
    "genre": "YA Fiction"
  },
  {
    "id": "twelve-the-naturals-4-5",
    "title": "Twelve (The Naturals, #4.5)",
    "author": "Barnes, Jennifer Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1692183905l/197002873.jpg",
    "dateFinished": "2025-10-05",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/197002873-twelve",
    "personalNote": "A quick little bonus story that let you spend just a bit more time with characters you love.",
    "pages": 144,
    "genre": "YA Fiction"
  },
  {
    "id": "the-light-we-lost",
    "title": "The Light We Lost",
    "author": "Santopolo, Jill",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1599183496l/55226030.jpg",
    "dateFinished": "2025-10-08",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/55226030-the-light-we-lost",
    "personalNote": "A bittersweet love story that definitely tugged at your heart, even if you wanted to yell at the characters sometimes.",
    "pages": 369,
    "genre": "Fiction"
  },
  {
    "id": "one-true-loves",
    "title": "One True Loves",
    "author": "Reid, Taylor Jenkins",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1559960507l/27189194.jpg",
    "dateFinished": "2025-10-12",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/27189194-one-true-loves",
    "personalNote": "You loved how this played with the idea of soulmates and second chances in such an emotional, TJR way.",
    "pages": 352,
    "genre": "Fiction"
  },
  {
    "id": "the-intruder",
    "title": "The Intruder",
    "author": "McFadden, Freida",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1746815530l/232571861.jpg",
    "dateFinished": "2025-10-14",
    "rating": 3,
    "goodreadsUrl": "https://www.goodreads.com/book/show/232571861-the-intruder",
    "personalNote": "Another Freida thriller to keep the suspense streak going, packed with exactly the kind of drama you expect.",
    "pages": 288,
    "genre": "Fiction"
  },
  {
    "id": "picking-daisies-on-sundays",
    "title": "Picking Daisies on Sundays",
    "author": "Cincotti, Liana",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1757053981l/236979743.jpg",
    "dateFinished": "2025-10-18",
    "rating": 1,
    "goodreadsUrl": "https://www.goodreads.com/book/show/236979743-picking-daisies-on-sundays",
    "personalNote": "This felt like such a soft, bittersweet little story, and I loved that it really stuck with you.",
    "pages": 256,
    "genre": "Fiction"
  },
  {
    "id": "fourth-wing-the-empyrean-1",
    "title": "Fourth Wing (The Empyrean, #1)",
    "author": "Yarros, Rebecca",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1667572773l/63219094.jpg",
    "dateFinished": "2025-11-02",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/63219094-fourth-wing",
    "personalNote": "Dragons, war college, and slow-burn angst—this book basically turned into a whole personality trait for a while.",
    "pages": 420,
    "genre": "Fiction"
  },
  {
    "id": "nothing-like-the-movies-better-than-the-movies-2",
    "title": "Nothing Like the Movies (Better Than the Movies #2)",
    "author": "Painter, Lynn",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1707300957l/207595482.jpg",
    "dateFinished": "2025-11-07",
    "rating": 4,
    "goodreadsUrl": "https://www.goodreads.com/book/show/207595482-nothing-like-the-movies",
    "personalNote": "A cute, movie-loving romcom that gave you all the tropey fun you needed in between heavier reads.",
    "pages": 448,
    "genre": "YA Fiction"
  },
  {
    "id": "we-were-liars",
    "title": "We Were Liars",
    "author": "Lockhart, E.",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1402749479l/16143347.jpg",
    "dateFinished": "2025-11-09",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/16143347-we-were-liars",
    "personalNote": "A dreamy, mysterious little book that left you turning the ending over in your mind afterward.",
    "pages": 242,
    "genre": "YA Fiction"
  },
  {
    "id": "the-last-one-at-the-wedding",
    "title": "The Last One at the Wedding",
    "author": "Rekulak, Jason",
    "coverImageUrl": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1711738371l/203590129.jpg",
    "dateFinished": "2025-11-15",
    "rating": 5,
    "goodreadsUrl": "https://www.goodreads.com/book/show/203590129-the-last-one-at-the-wedding",
    "personalNote": "A short, twisty little story that felt like the perfect quick read to close out another stretch of your year in books.",
    "pages": 39,
    "genre": "Fiction"
  }
] as const,
};
